### ISSUE TITLE
returned "Shared drive not found: drive ID

### ISSUE THREAD

**Issue by saitoh183** [atrpm/emby_gdrive_autoscan#5]
i did add my Videos folder ID 
```
Traceback (most recent call last):
  File "/data/scripts/emby_gdrive_autoscan/googleDriveService.py", line 157, in getChangesFromDrive
    pageSize=config['pageSize']).execute()
  File "/home/plex/.local/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/plex/.local/lib/python3.6/site-packages/googleapiclient/http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/drive/v3/changes?pageToken=REDACTED&spaces=drive&driveId=0B4SBUK6Y_ZyeR2MtNlBVRmJYd00&includeItemsFromAllDrives=true&supportsAllDrives=true&includeRemoved=true&fields=changes%28removed%2C+fileId%2C+file%28name%2C+parents%2C+mimeType%29%2C+time%29%2C+nextPageToken%2C+newStartPageToken&pageSize=100&alt=json returned "Shared drive not found: 0B4SBUK6Y_ZyeR2MtNlBVRmJYd00">
```
this is the url to my videos folder that contains my sub-folders
![image](https://user-images.githubusercontent.com/1534197/76036356-d91f2080-5f11-11ea-8351-4dab8e003927.png)

**Comment by atrpm** [comment]
That looks like a folder ID not a google drive ID. Are the files in a Shared/Team Drive or a personal Drive?

**Comment by saitoh183** [comment]
Gsuite... I tried with my root drive ID and got the same issue.. But i can try again

**Comment by saitoh183** [comment]
From what you said in the the emby post, I had to put the folder ID?

**Comment by saitoh183** [comment]
@atrpm 

So what could i be missing?

**Comment by hackmonker** [comment]
Does Shared Drive not work with this?
